server:
  port: 8080

spring:
  profiles:
    active: dao,service
  thymeleaf:
    cache: false

#logging:
#  level: debug


novel:
  defaultNovelId: 2019122517010269
  defaultChapterId: 2019122517010975
