server:
  port: 8080

spring:
  profiles:
    active: dao,service
  thymeleaf:
    cache: false

#logging:
#  level: debug


novel: #元尊
  defaultNovelId: 2020012819052215
  defaultChapterId: 2020012819052303
