##datasource##
spring:
  datasource:
    ### mybatis
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.16.1.200:3306/nx-purchasesale?characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/novel?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: dev123456
    ### druid
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true



  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      #host: 47.92.75.170
      host: 127.0.0.1
  #    host: 120.26.216.142
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: dev123456
      # 连接超时时间（毫秒）
      timeout: 30000
      pool:
      # 连接池最大连接数（使用负值表示没有限制）
        maxTotal: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWaitMillis: -1
      # 连接池中的最大空闲连接
        maxIdle: 8
      # 连接池中的最小空闲连接
        minIdle: 0
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test



### Mybatis
mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis.xml
  typeAliasesPackage: com.xiaokedou.novel.domain.po

#  typeAliases : com.lw.datacrab.db.criterion.DbQueryCriterion







